### PR TITLE
Discobot and Starred Communities Fixes

### LINKED ISSUE #7789: Can't star communities
## Describe the bug
Can't star communities on master right now. Likely caused by recent model changes.

### LINKED ISSUE #7790: Linking Discord Server to a new community throws incorrect errors
## Describe the bug
If you link a Discord server to a community and then try to link that server to another community we show an error saying 'Not an Admin' which is incorrect.

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #7790
Closed: #7789

## Description of Changes
- Added Tanstack Query for `setDiscordBotConfig` API calls
- Added `created_at` definition in `StarredCommunity.ts` Sequelize model
- Added transaction to `setDiscordBotConfig` API route
- Moved all Discord related routes to `routes/discord/` directory

## "How We Fixed It"

- This resolves #7790 because the initial request to the API returns the correct error but since the first call changes DB state, subsequent calls return a different error that is not useful to the client.
- This resolves #7789 because defining `createdAt` to be `created_at` tells Sequelize to automatically fill in `created_at` rather than `createdAt`. Thus `created_at` is no longer undefined/null.

## Test Plan
**For #7790**
- Start the commonwealth server
- In another terminal run `yarn workspace discord-bot start`
- In another terminal run `yarn workspace discord-bot start-consumer`
- Have an existing Discord server with Community forum feature enabled or create one: https://support.discord.com/hc/en-us/articles/6208479917079-Forum-Channels-FAQ
- Go to a community you are an admin of on Commonwealth that has never been connected to a Discord server or create one.
- Connect your Discord server to the community through the integrations page
- Go to another community you are an admin of (or create one)
- Attempt to link the same Discord server
  - You should get an error saying the Discord server is already linked to another community
- Go back to the original community
- Delete the Discord integration
- Go to your second community and you should be able to successfully link the Discord server

**For #7789**
From the sidebar try to star and unstar a variety of communities when you are signed in.

## Deployment Plan

1. 

## Other Considerations

- Thanks @masvelio for the infinite loop fix!

### CODE REVIEW

File: packages/commonwealth/server/routes/discord/setDiscordBotConfig.ts [hunk 1]
```diff
@@ -91,29 +91,38 @@ const setDiscordBotConfig = async (
...
     });
     log.info(
       'Attempted to add a guild that was already connected to another CW community.',
     );
 
+    try {
+      await transaction.commit();
+    } catch (err) {
+      await transaction.rollback();
+    }
```
Comment (rbennettcw) [inline packages/commonwealth/server/routes/discord/setDiscordBotConfig.ts:117]: Is there a reason not to wrap the previous logic from L99 in the try block?

**Review by rbennettcw — APPROVED** [review]

File: packages/commonwealth/server/routes/discord/setDiscordBotConfig.ts (hunk 1 above)
Comment (timolegros) [reply packages/commonwealth/server/routes/discord/setDiscordBotConfig.ts:117]: Good catch - this would leave txn hanging if something failed.

**Review by kurtisassad — APPROVED** [review]
