### PR TITLE
Bug fix: Edit Profile prepopulated data not rehydrating

### LINKED ISSUE #646: "Edit profile" prepopulated data fails to be updated after editing profile
- Go to profile page
- Edit your profile (eg change your name)
- Reopen edit profile form
- Old data is prefilled, not the latest data

In general we should avoid copying the app state to the local state because it will result in bugs like this, and has in other places too.

### PR DESCRIPTION
**Pull request by zakhap**
## Description

Added callback on the profile page to refresh the profile loading. It was an issue of mixing component state and app state.
Closes #646.

## Motivation and Context

Silly bug!

## How has this been tested?

- Go to profile page
- Edit your profile (eg change your name)
- Reopen edit profile form
- new data is prefilled, not the old data

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [x] no

### CODE REVIEW

File: client/scripts/views/pages/profile/index.ts [hunk 1]
```diff
@@ -96,6 +96,7 @@ interface IProfilePageState {
   comments: OffchainComment<any>[];
   loaded: boolean;
   loading: boolean;
+  refresh: boolean;
```
Comment (raykyri) [inline client/scripts/views/pages/profile/index.ts:99]: It is not clear what refresh does - can we use a more descriptive name to make the code self-documenting?
